language: elixir

sudo: false

elixir:
  - '1.6.6'
  - '1.7.4'
  - '1.8.2'
  - '1.9.4'
  - '1.10.4'
  - '1.11.4'

env:
  - MIX_ENV="test"

script:
  - mix compile --warnings-as-errors
  - mix format --check-formatted --dry-run
  - mix credo
  - mix coveralls

cache:
  directories:
    - _build
    - deps
