language: elixir

sudo: false

elixir:
  - '1.4.5'
  - '1.5.3'
  - '1.6.6'
  - '1.7.4'
  - '1.8.1'

env:
  - MIX_ENV="test"

script:
  - mix compile --warnings-as-errors
  - mix format --check-formatted --dry-run
  - mix credo
  - mix coveralls
  - travis_wait mix dialyzer --halt-exit-status

cache:
  directories:
    - _build
    - deps
